
name: team-hyper-accelerated-dragon CI/CD

on:
  push:
    branches:
      - main
  workflow_dispatch: # for manual triggering - may be removed later

jobs:
  run-tests:
  
    name: run-tests
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        
      - name: Set Up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          
      - name: Install Requirements/Dependencies
        run: 
          make requirements

      - name: Install Dev Requirements # Installs bandit, safety, coverage, flake8
        run: 
          make dev-setup 
          
      - name: Run Checks # # Runs security, runs unit tests, checks coverage 
        run:
          make run-checks

      - name: Lint with Flake8
        run:
          make run-linter
        continue-on-error: true # will keep the workflow from failing even if the linting step doesn't succeed

 
## Terraform to be added below 
